[project]
name = "pyscat"
version = "0.3"
authors = [
    {name = "Edgar", email = "edgar.gutierrez-fernandez@esrf.fr"},
]
readme = "README.md"

dependencies = [
    "numpy",
    "matplotlib",
    "pygix",
    "pyFAI",
    "PyQt5",
    "pandas",
    "h5py",
]

[tool.setuptools.packages.find]
where = ["pyxscat"]
include = ["*"]


[project.scripts]
pyxscat = "gui.run:run"