# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit, QLabel, QPushButton, QHBoxLayout, QListWidget
from silx.gui.plot.PlotWindow import Plot1D, Plot2D

class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.layout = QHBoxLayout()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1584, 860)
        self.centralwidget = QtWidgets.QWidget(MainWindow)


        button1 = QPushButton("One")
        button2 = QPushButton("Two")
        button3 = QPushButton("Three")
        button4 = QPushButton("Four")
        button5 = QPushButton("Five")

        self.layout.addWidget(button1)
        self.layout.addWidget(button2)
        self.layout.addWidget(button3)
        self.layout.addWidget(button4)
        self.layout.addWidget(button5)

        self.setLayout(self.layout)

    # def retranslateUi(self, MainWindow):
    #     _translate = QtCore.QCoreApplication.translate
    #     MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
    #     self.label_display_file.setText(_translate("MainWindow", "Displayed file:"))
    #     self.checkBox_live.setText(_translate("MainWindow", "Live"))
    #     self.checkBox_sub.setText(_translate("MainWindow", "Subtraction"))
    #     self.button_clear_chart.setText(_translate("MainWindow", "Clear"))
    #     self.button_save_chart.setText(_translate("MainWindow", " Save"))
    #     self.label_2.setText(_translate("MainWindow", "Save folder:"))
    #     self.comboBox_map.setItemText(0, _translate("MainWindow", "q (nm-1)"))
    #     self.comboBox_map.setItemText(1, _translate("MainWindow", "q (A-1)"))
    #     self.comboBox_map.setItemText(2, _translate("MainWindow", "2theta"))
    #     self.button_map.setText(_translate("MainWindow", "Generate map"))
    #     self.pushButton_savemap.setText(_translate("MainWindow", "Save map"))
    #     self.xticks.setText(_translate("MainWindow", "x-ticks:"))
    #     self.xlims.setText(_translate("MainWindow", "x-lims:"))
    #     self.yticks.setText(_translate("MainWindow", "y-ticks:"))
    #     self.ymin.setText(_translate("MainWindow", "y-lims:"))
    #     self.button_check_integration.setText(_translate("MainWindow", "Check"))
    #     self.button_plot.setText(_translate("MainWindow", "Plot"))
    #     self.button_average.setText(_translate("MainWindow", "Average"))
    #     self.header_items.setText(_translate("MainWindow", "Header items:"))
    #     self.label_beamline.setText(_translate("MainWindow", "Setup name:"))
    #     self.comboBox_setup.setItemText(0, _translate("MainWindow", "ALBA: BL11 (NCD-SWEET)"))
    #     self.comboBox_setup.setItemText(1, _translate("MainWindow", "ESRF: BM28 (XMaS)"))
    #     self.comboBox_setup.setItemText(2, _translate("MainWindow", "ESRF: BM26 (DUBBLE)"))
    #     self.checkBox_rotated.setText(_translate("MainWindow", "Rotated"))
    #     self.pushButton_qz.setText(_translate("MainWindow", "qz ||"))
    #     self.pushButton_qr.setText(_translate("MainWindow", "qr ||"))
    #     self.label_maindir.setText(_translate("MainWindow", "Main directory:"))
    #     self.lineEdit_maindir.setText(_translate("MainWindow", "/home/esrf/edgar1993a/Desktop/ALBA_NCD_Nov2022"))
    #     self.label_conditions.setText(_translate("MainWindow", "Conditions:"))
    #     self.lineEdit_conditions.setText(_translate("MainWindow", "*.edf"))
    #     self.label_ponifile.setText(_translate("MainWindow", "Ponifile:"))
    #     self.label_reference.setText(_translate("MainWindow", "Ref. folder:"))
    #     self.label_reference_2.setText(_translate("MainWindow", "Ref. file:"))
    #     self.button_pyfaicalib.setText(_translate("MainWindow", "pyFAI-calib2"))
    #     self.button_start.setText(_translate("MainWindow", "Update Data"))
    #     self.menuFile.setTitle(_translate("MainWindow", "Tools"))
    #     self.menuAbout.setTitle(_translate("MainWindow", "About"))
    #     self.actionAdd_new_setup.setText(_translate("MainWindow", "Add setup"))
    #     self.actionAdd_integration.setText(_translate("MainWindow", "Add integration"))
    #     self.actionAbout_PyXScat.setText(_translate("MainWindow", "About PyXScat"))

